name:                Latte
version:             0.1.0.0
author:              "Piotr Karpiński | pk394334@students.mimuw.edu.pl"

extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6.0.1
  - array
  - mtl >= 2.2.2
  - lens
  - extra
  - transformers >= 0.5.6.2
  - filepath
  - process
  - optparse-applicative


library:
  source-dirs:
    - src/latte
    - src/parser
executables:
  latc_x86:
    main:                Main.hs
    source-dirs:         src/main
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Latte

